services:
  app:
    image: ${DOCKER_USERNAME}/auth-service:latest
    platform: linux/amd64 # Add platform for compatibility with Apple Silicon
    volumes:
      - ./src:/usr/src/app/src
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/auth}
    depends_on:
      - mongodb
    command: |
      sh -c "npm install && npm run build && npm run start:prod"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  mongodb_data:
