services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT:-3000}:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/auth}
    depends_on:
      - mongodb
    command: |
      sh -c "if [ "$${NODE_ENV}" = "production" ]; then
        npm run build && node dist/main;
      else
        npm run start:dev;
      fi"
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

volumes:
  mongodb_data:
